services:
  - type: web
    name: MoviesHCI
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn MoviesHCI.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MoviesHCI.settings